services:
  postgres:
    container_name: nestjs_auth_pg
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - 'nestjs-auth-pg:/var/lib/postgresql/data'

  api:
    container_name: nestjs_auth_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8080
    environment:
      - DATABASE_URL=${DATABASE_URL_CONTAINER}
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:${POSTGRES_PORT}",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
